root: true
parserOptions:
  project: 'tsconfig.json'
extends:
  - airbnb-typescript
  - airbnb-typescript-prettier
parser: '@typescript-eslint/parser'
settings:
  react:
    version: 'detect'
plugins:
  - '@typescript-eslint'
rules:
  import/extensions: [0, { <js>: 'always' }]
  guard-for-in: 0
  import/no-unresolved: 0
  comma-dangle: 0
  arrow-body-style: 0
  no-underscore-dangle: 0
  class-methods-use-this: 0
  camelcase: 0
  import/prefer-default-export: 0
  no-useless-constructor: 0
  no-shadow: 0
  max-classes-per-file: 0
  no-param-reassign: 0
  no-return-assign: 0
  '@typescript-eslint/interface-name-prefix': 0
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/no-non-null-assertion': 0
  '@typescript-eslint/ban-ts-ignore': 0
  '@typescript-eslint/ban-types': 0
  '@typescript-eslint/ban-ts-comment': 0
  '@typescript-eslint/no-empty-function': 0
  func-names: 0
  import/no-cycle: 0
  '@typescript-eslint/no-unused-vars': 0
  no-unused-expressions: 0
  '@typescript-eslint/no-unused-expressions': 0
  no-restricted-syntax: 0
  no-await-in-loop: 0
  '@typescript-eslint/naming-convention':
    - error
    - selector: variableLike
      format:
        - snake_case
        - UPPER_CASE
    - selector: parameter
      format:
        - camelCase
        - snake_case
      leadingUnderscore: allow
    - selector: variable
      format:
        - snake_case
        - UPPER_CASE
      types:
        - boolean
      prefix:
        - is_
        - should_
        - has_
        - can_
        - did_
        - will_
        - IS_
        - SHOULD_
        - HAS_
        - CAN_
        - DID_
        - WILL_
    - selector: typeLike
      format:
        - PascalCase
      leadingUnderscore: forbid
      trailingUnderscore: forbid
env:
  mocha: true
