version: '3.3'
services:
  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_USERNAME}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_USERNAME}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mysql-storage:/var/lib/mysql
  rabbit:
    image: rabbitmq:3.8.3-management
    container_name: 'rabbitmq-server'
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

    ports:
      - '${RABBITMQ_PORT}:5672'
      - 15672:15672
    volumes:
      - ${PWD}/rabbit_config.json:/etc/rabbitmq/definitions.json
      - rabbitmq-storage:/var/lib/rabbitmq

  redis:
    image: 'redis:alpine'
    container_name: 'redis-server'
    command: redis-server
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-storage:/var/lib/redis
      - redis-storage:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo-storage:/var/lib/mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      
  server-grpc:
      image: cirosda/server-grpc:latest
      container_name: go-server-grpc
      restart: always
      ports:
          - "50044:50044"
      
volumes:
  mysql-storage:
  mongo-storage:
  redis-storage:
  rabbitmq-storage:
