apiVersion: v1
kind: Service
metadata:
  name: "$PROJECT_NAME"
  namespace: "$NAMESPACE"
  labels:
    app: "$PROJECT_NAME"
    service: "$PROJECT_NAME"
spec:
  ports:
  - port: $SERVICEPORT
    name: http
  selector:
    app: "$PROJECT_NAME"
