name: deploy
inputs:
  token: 
     description: "token"
     required: true
  cluster: 
     description: "cluster"
     required: true
  namespace: 
     description: "namespace"
     required: true
  branch: 
     description: "namespace"
     required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: ciro-stodulski/flux
        token: ${{ inputs.token }} # `GH_PAT` is a secret that contains your PAT
    
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: deployments
        path: scripts/kubernetes
  
    - name: Install and commit flux
      shell: bash
      run: |
          git config --global user.name ciro-stodulski
          git config --global user.email ciro-stodulski@github.com
          mkdir -p ${{ inputs.cluster }}/ ${{ inputs.namespace }}
          mkdir -p ${{ inputs.cluster }}/${{ inputs.namespace }}/${{ github.event.repository.name }}
          cp -r scripts/kubernetes/*.yaml  ${{ inputs.cluster }}/lab/${{ github.event.repository.name }}
          rm -rf scripts
          git add .
          git status
          git commit -m "$(git rev-parse --short "$GITHUB_SHA")"
          git push origin ${{ inputs.branch }}
