name: deploy
inputs:
  token: 
     description: "token"
     required: true
  cluster: 
     description: "cluster"
     required: true
  namespace: 
     description: "namespace"
     required: true

runs:
  using: 'composite'
  steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: create flux repo
      shell: bash
      run: |
        mkdir repo-folder-flux
        cd repo-folder-flux

    - name: Checkout private tools
      uses: actions/checkout@v3
      with:
        repository: ciro-stodulski/flux
        token: ${{ inputs.token }} # `GH_PAT` is a secret that contains your PAT
    
    - name: return root path
      shell: bash
      run: |
          cd ..

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: deployments
        path: scripts/kubernetes
  
    - name: Install and commit flux
      shell: bash
      run: |
          git config --global user.name ciro-stodulski
          git config --global user.email ciro-stodulski@github.com
          mkdir -p ${{ inputs.cluster }}/ ${{ inputs.namespace }}
          mkdir -p ${{ inputs.cluster }}/${{ inputs.namespace }}/${{ github.event.repository.name }}
          cp -r scripts/kubernetes/*  ${{ inputs.cluster }}/lab/${{ github.event.repository.name }}
          rm -rf scripts
          git add .
          git status
          git commit -m "$(git rev-parse --short "$GITHUB_SHA")"
          git push origin develop
      # criar diretorio dentro do pasta 
      # git add .
      # git commit -m "generated"
      # git pull
      # git push
      # npm ci
      # npm run ts -- scripts/commands/commit-flux.ts