name: deploy

runs:
  using: 'composite'
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: dist

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Push docker image
      shell: bash
      run: |
        docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/${{ github.event.repository.name }}:$(git rev-parse --short "$GITHUB_SHA")
        docker push ${{secrets.DOCKER_USERNAME}}/${{ github.event.repository.name }}:$(git rev-parse --short "$GITHUB_SHA")
