name: Manual deployment to staging

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
env:
  ECR_REPOSITORY: content

jobs:
  build_and_deploy:
    name: Build and deploy to develop

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Executing Publish
      uses: ciro-stodulski/actions/cd/publish@develop
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        docker_password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Executing Deploy
      uses: ciro-stodulski/actions/cd/deploy@develop
      with:
        token: ${{ secrets.GH_PAT }} 
        cluster: ${{ secrets.CLUSTER }} 
        namespace: ${{ secrets.NAMESPACE }}
        branch: ${{ steps.prepare_branch.outputs.branch }}
