name: pull-request 

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:    
  extract-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Executing Pull Request
      uses: ciro-stodulski/tsnode-clean-api/.github/templates/pull-request@feat/pipeline
      with:
        version: v1.0.0
        namespace: "${{ steps.extract_branch.outputs.branch }}"

#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Executing Build
#       uses: ./.github/templates/build
#       with:
#         version: v1.0.0
#         namespace: "${{ steps.extract_branch.outputs.branch }}"
#       if: ${{ steps.extract_branch.outputs.branch == 'develop' || steps.extract_branch.outputs.branch == 'main' }}

#   publish:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Executing Publish
#       uses: ./.github/templates/publish
#       with:
#         version: v1.0.0
#         namespace: "${{ steps.extract_branch.outputs.branch }}"
#       if: ${{ steps.extract_branch.outputs.branch == 'develop' || steps.extract_branch.outputs.branch == 'main' }}

#   # deploy:
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #   - name: Executing Deploy
#   #     uses: ./.github/templates/deploy
#   #     with:
#   #       version: v1.0.0
#   #       namespace: "${{ steps.extract_branch.outputs.branch }}"
#   #     if: ${{ steps.extract_branch.outputs.branch == 'develop' || steps.extract_branch.outputs.branch == 'main' }}