name: pull-request
# Were we can define the inputs that our action will accept
runs:
  using: "composite"
  steps:
      - name: Use Node.js ${{ matrix.node-version }}
        shell: bash
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: |
          npm ci
          npm run build --if-present
          npm run lint
          npm test
